print(1 > 2)  # False
print(2 > 1)  # True
print(2 >= 2)  # True
print(2 >= 3)  # False
print(2 == 2)  # True
print(2 == 3)  # False
print(2 != 3)  # True
print(2 != 2)  # False
print(2 == ("2"))  # False 